export const IDENTITY_MAIL_INDEPENDENT_SECRET_KEYS = [
  'JWT_SECRET',
  'GUEST_PORTAL_JWT_SECRET',
  'GUEST_GAME_REFERRAL_SECRET',
  'APP_ENCRYPTION_KEY',
  'INTEGRATION_ENCRYPTION_KEY',
  'IDENTITY_EMAIL_FINGERPRINT_HMAC_KEY',
  'SYNC_SERVICE_TOKEN',
] as const;
