import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { canonical, digest } from './contract.mjs';
import { EXTERNAL_WORKER_GRANT_CONTRACT, EXTERNAL_WORKER_IDENTITY, EXTERNAL_WORKER_RESULT_CONTRACT, parseExternalWorkerResult, validateExternalWorkerGrant, validateExternalWorkerResult } from './external-worker-contract.mjs';

const keys = crypto.generateKeyPairSync('ed25519'), publicKey = keys.publicKey.export({ type: 'spki', format: 'pem' });
const host = 'a'.repeat(64), releaseSha = 'b'.repeat(40), runId = '12345678-1234-4123-8123-123456789abc';
const profile = (mode = 'CANARY') => ({ DATABASE_URL: 'postgresql://leetplus_runtime:fixture@postgres/leetplus?schema=public&connection_limit=1&pool_timeout=5&connect_timeout=5&sslmode=require&sslcert=/run/secrets/db-ca.pem&sslaccept=strict', INTEGRATION_ENCRYPTION_KEY: 'i', APP_ENCRYPTION_KEY: 'a', LANGAME_EXTERNAL_WORKER_ENABLED: 'true', LANGAME_EXTERNAL_WORKER_LIVE: 'true', LANGAME_EXTERNAL_WORKER_MODE: mode, LANGAME_EXTERNAL_WORKER_TENANT_ID: EXTERNAL_WORKER_IDENTITY.tenantId, LANGAME_EXTERNAL_WORKER_TENANT_SLUG: EXTERNAL_WORKER_IDENTITY.tenantSlug, LANGAME_EXTERNAL_WORKER_SOURCE_ID: EXTERNAL_WORKER_IDENTITY.sourceId, LANGAME_EXTERNAL_WORKER_STORE_ID: EXTERNAL_WORKER_IDENTITY.storeId, LANGAME_EXTERNAL_WORKER_DOMAIN: EXTERNAL_WORKER_IDENTITY.domain, LANGAME_EXTERNAL_WORKER_CLUB_ID: EXTERNAL_WORKER_IDENTITY.clubId, LANGAME_EXTERNAL_WORKER_EXECUTION_REVISION: '1', LANGAME_EXTERNAL_WORKER_PROFILE_REVISION: '2', LANGAME_EXTERNAL_WORKER_STORE_REVISION: '0', LANGAME_EXTERNAL_WORKER_CUSTOMER_STAGE: 'LIVE', LANGAME_DISCREPANCY_LOG_ROOT: '/var/lib/leetplus/langame-sync', LANGAME_DAILY_SYNC_SCHEDULER_ENABLED: 'false', LANGAME_SCHEDULED_HTTP_ENABLED: 'false', GUEST_GAME_BONUS_LEDGER_SCHEDULER_ENABLED: 'false', ...(mode === 'CANARY' ? { LANGAME_EXTERNAL_WORKER_DATE: '2026-09-26' } : {}) });
function fixture(mode = 'CANARY') { const bytes = Buffer.from(canonical(profile(mode))), grant = { contract: EXTERNAL_WORKER_GRANT_CONTRACT, id: crypto.randomUUID(), worker: EXTERNAL_WORKER_IDENTITY.worker, mode, hostIdentitySha256: host, releaseSha, generation: 3, ...EXTERNAL_WORKER_IDENTITY, executionRevision: 1, profileRevision: 2, storeRevision: 0, secretSha256: digest(bytes), issuedAt: '2026-09-26T00:00:00.000Z', expiresAt: mode === 'CANARY' ? '2026-09-26T03:00:00.000Z' : '2026-10-01T00:00:00.000Z', businessDate: mode === 'CANARY' ? '2026-09-26' : null }; return { bytes, grant, envelope: { grant, signature: crypto.sign(null, Buffer.from(canonical(grant)), keys.privateKey).toString('base64') }, active: { activeSlot: 'blue', generation: 3, blue: { releaseSha } } }; }
function signedWithProfile(f, value) { const bytes = Buffer.from(canonical(value)), grant = { ...f.grant, secretSha256: digest(bytes) }; return { bytes, envelope: { grant, signature: crypto.sign(null, Buffer.from(canonical(grant)), keys.privateKey).toString('base64') } }; }
test('validates exact signed external grant and strict profile', () => { const f = fixture(); assert.equal(validateExternalWorkerGrant(f.envelope, publicKey, f.active, host, f.bytes, Date.parse('2026-09-26T01:00:00Z')).worker, EXTERNAL_WORKER_IDENTITY.worker); });
test('rejects identity, revision, date, signature, expiry and profile scope widening', () => { const f = fixture(); for (const [field, value] of [['tenantId', crypto.randomUUID()], ['sourceId', crypto.randomUUID()], ['storeId', crypto.randomUUID()], ['executionRevision', 2], ['businessDate', '2026-09-25']]) { const grant = { ...f.grant, [field]: value }; const envelope = { grant, signature: crypto.sign(null, Buffer.from(canonical(grant)), keys.privateKey).toString('base64') }; assert.throws(() => validateExternalWorkerGrant(envelope, publicKey, f.active, host, f.bytes, Date.parse('2026-09-26T01:00:00Z'))); }
  assert.throws(() => validateExternalWorkerGrant({ ...f.envelope, signature: 'A'.repeat(88) }, publicKey, f.active, host, f.bytes, Date.parse('2026-09-26T01:00:00Z')));
  assert.throws(() => validateExternalWorkerGrant(f.envelope, publicKey, f.active, host, f.bytes, Date.parse('2026-09-27T01:00:00Z')));
  validateExternalWorkerGrant(f.envelope, publicKey, f.active, host, f.bytes, Date.parse('2026-09-27T01:00:00Z'), { allowExpired: true });
  const widened = signedWithProfile(f, { ...profile(), LANGAME_DAILY_SYNC_SCHEDULER_ENABLED: 'true' }); assert.throws(() => validateExternalWorkerGrant(widened.envelope, publicKey, f.active, host, widened.bytes, Date.parse('2026-09-26T01:00:00Z')), /scheduler/);
  const db = signedWithProfile(f, { ...profile(), DATABASE_URL: profile().DATABASE_URL.replace('connection_limit=1', 'connection_limit=3') }); assert.throws(() => validateExternalWorkerGrant(db.envelope, publicKey, f.active, host, db.bytes, Date.parse('2026-09-26T01:00:00Z')), /DB option/);
  const extra = signedWithProfile(f, { ...profile(), REDIS_URL: 'redis://redis' }); assert.throws(() => validateExternalWorkerGrant(extra.envelope, publicKey, f.active, host, extra.bytes, Date.parse('2026-09-26T01:00:00Z')), /forbidden key/);
  const absentLogRoot = signedWithProfile(f, Object.fromEntries(Object.entries(profile()).filter(([key]) => key !== 'LANGAME_DISCREPANCY_LOG_ROOT'))); validateExternalWorkerGrant(absentLogRoot.envelope, publicKey, f.active, host, absentLogRoot.bytes, Date.parse('2026-09-26T01:00:00Z'));
  const wrongLogRoot = signedWithProfile(f, { ...profile(), LANGAME_DISCREPANCY_LOG_ROOT: '/tmp' }); assert.throws(() => validateExternalWorkerGrant(wrongLogRoot.envelope, publicKey, f.active, host, wrongLogRoot.bytes, Date.parse('2026-09-26T01:00:00Z')), /log root/);
});
test('parses fresh result and rejects replay as fresh or malformed stdout', () => { const f = fixture(), base = { contract: EXTERNAL_WORKER_RESULT_CONTRACT, worker: EXTERNAL_WORKER_IDENTITY.worker, runId, mode: f.grant.mode, businessDate: f.grant.businessDate, tenantId: EXTERNAL_WORKER_IDENTITY.tenantId, tenantSlug: EXTERNAL_WORKER_IDENTITY.tenantSlug, sourceId: EXTERNAL_WORKER_IDENTITY.sourceId, storeId: EXTERNAL_WORKER_IDENTITY.storeId, profileRevision: 2, executionRevision: 1, storeRevision: 0, decision: 'SUCCESS', partialScopes: [], failedScopes: [], replayed: false, originalRunId: null };
  assert.equal(parseExternalWorkerResult(`${JSON.stringify(base)}\n`, { runId, grant: f.grant, businessDate: '2026-09-26' }).decision, 'SUCCESS');
  assert.throws(() => parseExternalWorkerResult(canonical(base), { runId, grant: f.grant, businessDate: '2026-09-26' }));
  const replay = { ...base, runId: '22345678-1234-4123-8123-123456789abc', replayed: true, originalRunId: '22345678-1234-4123-8123-123456789abc' };
  assert.throws(() => validateExternalWorkerResult(replay, { runId, grant: f.grant, businessDate: '2026-09-26' }));
  assert.equal(validateExternalWorkerResult(replay, { runId, grant: f.grant, businessDate: '2026-09-26', allowReplayed: true }).replayed, true);
});
test('TIMER result uses native previous-Yekaterinburg business date', () => { const f = fixture('TIMER'), result = { contract: EXTERNAL_WORKER_RESULT_CONTRACT, worker: EXTERNAL_WORKER_IDENTITY.worker, runId, mode: 'TIMER', businessDate: '2026-09-26', tenantId: EXTERNAL_WORKER_IDENTITY.tenantId, tenantSlug: EXTERNAL_WORKER_IDENTITY.tenantSlug, sourceId: EXTERNAL_WORKER_IDENTITY.sourceId, storeId: EXTERNAL_WORKER_IDENTITY.storeId, profileRevision: 2, executionRevision: 1, storeRevision: 0, decision: 'SUCCESS', partialScopes: [], failedScopes: [], replayed: false, originalRunId: null };
  assert.equal(validateExternalWorkerResult(result, { runId, grant: f.grant, businessDate: '2026-09-26' }).businessDate, '2026-09-26');
  assert.throws(() => validateExternalWorkerResult({ ...result, businessDate: '2026-09-25' }, { runId, grant: f.grant, businessDate: '2026-09-26' }));
});
