import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { canonical, digest, EXTERNAL_WORKER_CAPABILITY } from './contract.mjs';
import { EXTERNAL_WORKER_IDENTITY } from './external-worker-contract.mjs';
import { deriveWorkerContinuation } from './worker-continuation.mjs';
import { deriveWorkerSetV3, validateWorkerSetEnvelopes, validateWorkerSetV3, workerSetNames } from './worker-set-v3.mjs';

const keys = crypto.generateKeyPairSync('ed25519'), pub = keys.publicKey.export({ type: 'spki', format: 'pem' });
const externalKeys = crypto.generateKeyPairSync('ed25519'), externalPub = externalKeys.publicKey.export({ type: 'spki', format: 'pem' });
const signExternal = grant => ({ grant, signature: crypto.sign(null, Buffer.from(canonical(grant)), externalKeys.privateKey).toString('base64') });
const host = 'a'.repeat(64), previous = 'b'.repeat(40), target = 'c'.repeat(40);
const workers = ['bonus-ledger-worker', 'langame-daily-worker'];
const profiles = Object.fromEntries(workers.map(worker => { const prefix = worker === workers[0] ? 'GUEST_BONUS_LEDGER_WORKER' : 'LANGAME_DAILY_WORKER'; return [worker, Buffer.from(canonical({ DATABASE_URL: 'postgresql://leetplus_runtime:x@postgres/leetplus?schema=public&connection_limit=2&pool_timeout=5&connect_timeout=5&sslmode=require&sslcert=/run/secrets/db-ca.pem&sslaccept=strict', [`${prefix}_TENANT_SLUG`]: 'tenant', [`${prefix}_CANARY`]: 'false' }))]; }));
const sign = grant => ({ grant, signature: crypto.sign(null, Buffer.from(canonical(grant)), keys.privateKey).toString('base64') });
function legacy() { const originals = workers.map(worker => sign({ contract: 'LEETPLUS_COMPOSE_BLUE_GREEN_V1_WORKER_GRANT', worker, mode: 'TIMER', id: crypto.randomUUID(), hostIdentitySha256: host, releaseSha: previous, generation: 8, tenantSlug: 'tenant', secretSha256: digest(profiles[worker]), issuedAt: '2026-09-26T00:00:00.000Z', expiresAt: '2026-10-01T00:00:00.000Z' })); return deriveWorkerContinuation({ originalTimers: workers.map((worker, i) => ({ worker, unit: i ? 'leetplus-compose-daily.timer' : 'leetplus-compose-bonus.timer', enabled: true, active: true })), originalGrantEnvelopes: originals, profileBindings: workers.map(worker => ({ worker, profileSha256: digest(profiles[worker]) })), targetReleaseSha: target, currentGeneration: 8, previousReleaseSha: previous, forwardGrantIds: ['12345678-1234-4123-8123-123456789abc', '22345678-1234-4123-8123-123456789abc'], rollbackGrantIds: ['32345678-1234-4123-8123-123456789abc', '42345678-1234-4123-8123-123456789abc'] }); }
function external(present = false) { if (!present) return { worker: EXTERNAL_WORKER_IDENTITY.worker, preimage: 'ABSENT_AUTHORITY', originalGrantEnvelope: null, profileSha256: null, enrollmentReceiptSha256: null, originalTimer: { unit: 'leetplus-compose-external-daily.timer', loadState: 'not-found', enabled: false, active: false, subState: 'dead' }, forward: { state: 'DORMANT', grant: null }, rollback: { state: 'ABSENT_UNSUPPORTED', grant: null } }; const bytes = Buffer.from(canonical({ DATABASE_URL: 'postgresql://leetplus_runtime:x@postgres/leetplus?schema=public&connection_limit=1&pool_timeout=5&connect_timeout=5&sslmode=require&sslcert=/run/secrets/db-ca.pem&sslaccept=strict', INTEGRATION_ENCRYPTION_KEY: 'i', APP_ENCRYPTION_KEY: 'a', LANGAME_EXTERNAL_WORKER_ENABLED: 'true', LANGAME_EXTERNAL_WORKER_LIVE: 'true', LANGAME_EXTERNAL_WORKER_MODE: 'TIMER', LANGAME_EXTERNAL_WORKER_TENANT_ID: EXTERNAL_WORKER_IDENTITY.tenantId, LANGAME_EXTERNAL_WORKER_TENANT_SLUG: EXTERNAL_WORKER_IDENTITY.tenantSlug, LANGAME_EXTERNAL_WORKER_SOURCE_ID: EXTERNAL_WORKER_IDENTITY.sourceId, LANGAME_EXTERNAL_WORKER_STORE_ID: EXTERNAL_WORKER_IDENTITY.storeId, LANGAME_EXTERNAL_WORKER_DOMAIN: EXTERNAL_WORKER_IDENTITY.domain, LANGAME_EXTERNAL_WORKER_CLUB_ID: '1', LANGAME_EXTERNAL_WORKER_EXECUTION_REVISION: '1', LANGAME_EXTERNAL_WORKER_PROFILE_REVISION: '1', LANGAME_EXTERNAL_WORKER_STORE_REVISION: '0', LANGAME_EXTERNAL_WORKER_CUSTOMER_STAGE: 'LIVE', LANGAME_DAILY_SYNC_SCHEDULER_ENABLED: 'false', LANGAME_SCHEDULED_HTTP_ENABLED: 'false', GUEST_GAME_BONUS_LEDGER_SCHEDULER_ENABLED: 'false' })); const grant = { contract: 'LEETPLUS_LANGAME_EXTERNAL_WORKER_GRANT_V1', id: crypto.randomUUID(), worker: EXTERNAL_WORKER_IDENTITY.worker, mode: 'TIMER', hostIdentitySha256: host, releaseSha: previous, generation: 8, ...EXTERNAL_WORKER_IDENTITY, executionRevision: 1, profileRevision: 1, storeRevision: 0, secretSha256: digest(bytes), issuedAt: '2026-09-26T00:00:00.000Z', expiresAt: '2026-10-01T00:00:00.000Z', businessDate: null }; const value = { worker: EXTERNAL_WORKER_IDENTITY.worker, preimage: 'PRESENT', originalGrantEnvelope: signExternal(grant), profileSha256: digest(bytes), enrollmentReceiptSha256: 'd'.repeat(64), originalTimer: { unit: 'leetplus-compose-external-daily.timer', loadState: 'loaded', enabled: true, active: true, subState: 'waiting' }, forward: { state: 'DORMANT', grant: null }, rollback: { state: 'ABSENT_UNSUPPORTED', grant: null } }; Object.defineProperty(value, 'bytes', { value: bytes }); return value; }
function releases(all = false) { return { forward: { releaseSha: target, ...(all ? { externalWorkerCapability: EXTERNAL_WORKER_CAPABILITY } : {}) }, rollback: { releaseSha: previous, ...(all ? { externalWorkerCapability: EXTERNAL_WORKER_CAPABILITY } : {}) } }; }
test('first absent authority keeps V2 byte identity and creates no external grant', () => { const old = legacy(), ext = external(), r = releases(); const policy = deriveWorkerSetV3({ legacy: old, external: ext, forwardRelease: r.forward, rollbackRelease: r.rollback }); assert.equal(canonical(policy.legacy), canonical(old)); assert.equal(policy.external.forward.state, 'ABSENT_UNSUPPORTED'); assert.equal(policy.external.rollback.state, 'ABSENT_UNSUPPORTED'); assert.deepEqual(workerSetNames(policy), [...workers, EXTERNAL_WORKER_IDENTITY.worker]); });
test('present external authority derives all three workers for capable forward and rollback', () => { const old = legacy(), ext = external(true), r = releases(true); const policy = deriveWorkerSetV3({ legacy: old, external: ext, forwardRelease: r.forward, rollbackRelease: r.rollback, forwardGrantId: '52345678-1234-4123-8123-123456789abc', rollbackGrantId: '62345678-1234-4123-8123-123456789abc' }); assert.equal(policy.external.forward.grant.generation, 9); assert.equal(policy.external.rollback.grant.generation, 10); assert.equal(policy.external.forward.grant.releaseSha, target); assert.equal(policy.external.rollback.grant.releaseSha, previous); });
test('rejects missing capability, IDs, signatures and tampered V3 bindings', () => { const old = legacy(), ext = external(true), r = releases(true); assert.throws(() => deriveWorkerSetV3({ legacy: old, external: ext, forwardRelease: r.forward, rollbackRelease: r.rollback })); const policy = deriveWorkerSetV3({ legacy: old, external: ext, forwardRelease: r.forward, rollbackRelease: r.rollback, forwardGrantId: '52345678-1234-4123-8123-123456789abc', rollbackGrantId: '62345678-1234-4123-8123-123456789abc' }), plan = { targetSlot: 'forward', forward: r.forward, previous: { activeSlot: 'rollback', rollback: r.rollback }, generation: 8 }; assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, profileSha256: 'e'.repeat(64) } }, plan)); assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, originalGrantEnvelope: { grant: ext.originalGrantEnvelope.grant } } }, plan)); assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, forward: { ...policy.external.forward, grant: { ...policy.external.forward.grant, sourceId: crypto.randomUUID() } } } }, plan)); assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, forward: { ...policy.external.forward, grant: { ...policy.external.forward.grant, releaseSha: previous } } } }, plan)); assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, rollback: { ...policy.external.rollback, grant: { ...policy.external.rollback.grant, id: ext.originalGrantEnvelope.grant.id } } } }, plan)); assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, originalGrantEnvelope: { ...policy.external.originalGrantEnvelope, grant: { ...ext.originalGrantEnvelope.grant, profileRevision: 0 } } } }, plan)); assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, originalGrantEnvelope: { ...policy.external.originalGrantEnvelope, grant: { ...ext.originalGrantEnvelope.grant, secretSha256: 'z'.repeat(64) } } } }, plan)); assert.throws(() => validateWorkerSetV3({ ...policy, external: { ...policy.external, originalGrantEnvelope: { ...policy.external.originalGrantEnvelope, grant: { ...ext.originalGrantEnvelope.grant, expiresAt: '2027-01-01T00:00:00.000Z' } } } }, plan)); assert.throws(() => validateWorkerSetV3(policy, { ...plan, forward: { ...r.forward, externalWorkerCapability: 'UNKNOWN' } })); const unsupported = deriveWorkerSetV3({ legacy: old, external: ext, forwardRelease: r.forward, rollbackRelease: { releaseSha: previous }, forwardGrantId: '52345678-1234-4123-8123-123456789abc' }); assert.equal(unsupported.external.rollback.state, 'ABSENT_UNSUPPORTED'); });
test('envelope validator binds legacy and external signatures to separate roots and current state', () => { const old = legacy(), ext = external(true), r = releases(true), policy = deriveWorkerSetV3({ legacy: old, external: ext, forwardRelease: r.forward, rollbackRelease: r.rollback, forwardGrantId: '52345678-1234-4123-8123-123456789abc', rollbackGrantId: '62345678-1234-4123-8123-123456789abc' }); const context = { plan: { targetSlot: 'forward', forward: r.forward, previous: { activeSlot: 'rollback', rollback: r.rollback }, generation: 8 }, publicKey: pub, externalPublicKey: externalPub, active: { activeSlot: 'blue', generation: 8, blue: { releaseSha: previous } }, hostIdentitySha256: host, profiles, externalProfile: ext.bytes, now: Date.parse('2026-09-26T01:00:00Z') }, input = { ...context, stage: 'CURRENT', legacyEnvelopes: old.originalGrantEnvelopes, externalEnvelope: ext.originalGrantEnvelope }; validateWorkerSetEnvelopes(policy, input); assert.throws(() => validateWorkerSetEnvelopes(policy, { ...input, externalPublicKey: pub }), /Dedicated/); assert.throws(() => validateWorkerSetEnvelopes(policy, { ...input, externalEnvelope: { grant: ext.originalGrantEnvelope.grant, signature: 'bad' } })); });
